# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name:               "A Debunk Place"

author:
  # facebook:         your-id
  # youtubeUser:      your-id
  # youtubeChannel:   your-id
  # twitter:          your-id
  github:           perfiffer
  # stackoverflow:    your-id
  # quora:            your-id
  # linkedin:         your-id
  # pinterest:        your-id
  # googlePlus:       your-id
  # instagram:        your-id
  # reddit:           your-id
  # medium:           your-id
  # tumblr:           your-id
  email:            perfiffer@163.com
  jianshu:          12c8dec9926b

copyright:
  year:             2019
  name:             Perfiffer

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "kiko-plus"

# Gitalk
gitalk: 
  enable: true
  id: 236b7ddc38038bad0810
  secret: 6c14082b80b0054a468c68bfca88edd914a80fd9

# URL
url:                "https://perfiffer.github.io" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/ShangHai
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
 - name:           "H"
   url:            "/"
   class:          "fa fa-home"
 - name:           "About"
   url:            "/about"
   class:          "fa fa-info"
 - name:           "A"
   url:            "/archive"
   class:          "fa fa-file-archive"
 - name:           "T"
   url:            "/tags"
   class:          "fa fa-tags"
# - name:           "Github"
#   url:            "https://github.com/perfiffer"

# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
